# Generated by Django 5.2.15 on 2026-06-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PalmDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('flow', 'Flow'), ('process', 'Process'), ('resource', 'Resource'), ('state_schema', 'State schema')], db_index=True, max_length=32)),
                ('definition_id', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Palm definition',
                'verbose_name_plural': 'Palm definitions',
                'indexes': [models.Index(fields=['kind', 'name'], name='palm_django_def_kind_name_idx')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'definition_id'), name='palm_django_definition_kind_id_uniq')],
            },
        ),
        migrations.CreateModel(
            name='PalmProcessInstance',
            fields=[
                ('instance_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('job_id', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(db_index=True, max_length=64)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Palm process instance',
                'verbose_name_plural': 'Palm process instances',
                'indexes': [models.Index(fields=['status', 'updated_at'], name='palm_django_inst_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='PalmStorageEntry',
            fields=[
                ('key', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('namespace', models.CharField(db_index=True, max_length=64)),
                ('value', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Palm storage entry',
                'verbose_name_plural': 'Palm storage entries',
                'indexes': [models.Index(fields=['namespace', 'updated_at'], name='palm_django_kv_ns_idx')],
            },
        ),
    ]
